config/routes.rb
Rails.application.routes.draw do
  root "gossips#index"

  resources :users, only: [:show, :new, :create]

  resources :gossips do
    resources :comments, only: [:create, :destroy, :edit, :update, :show] do
      resource :like, only: [:create, :destroy]
    end
    resource :like, only: [:create, :destroy]
  end

  resources :cities, only: [:show]
  resources :tags, only: [:show]

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/:first_name', to: 'static_pages#welcome', as: 'welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # 💬 Routes pour la messagerie
  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :city

  has_many :gossips
  has_many :comments
  has_many :likes

  has_many :sent_conversations, foreign_key: :sender_id, class_name: 'Conversation'
  has_many :received_conversations, foreign_key: :recipient_id, class_name: 'Conversation'

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  # Méthode utilitaire pour afficher le nom complet
  def full_name
    "#{first_name} #{last_name}"
  end

  # Méthode pour stocker le remember_digest à partir d’un token
  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end





  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper  # Ajout pour accéder à remember()

  def show
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Utilisateur non trouvé."
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      # Si l'utilisateur a coché "Se souvenir de moi", on crée les cookies
      remember(@user) if params[:remember_me] == "1"

      redirect_to root_path, notice: "Bienvenue #{@user.first_name} !"
    else
      Rails.logger.info @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :city_id)
  end
end




  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |form| %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :city_id %>
  <%= form.collection_select :city_id, City.all, :id, :name %>

  <div>
    <%= check_box_tag :remember_me, "1" %>
    <%= label_tag :remember_me, "Se souvenir de moi" %>
  </div>

  <%= form.submit "S'inscrire" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>
  <p>Description : <%= @user.description %></p>
  <p>Age : <%= @user.age %></p>
  <p>Email : <%= @user.email %></p>
  <p>Ville : <%= link_to @user.city.name, city_path(@user.city) %></p>

  <hr>
  <h3>Potins publiés :</h3>
  <% if @user.gossips.any? %>
    <ul class="list-group">
      <% @user.gossips.each do |gossip| %>
        <li class="list-group-item">
          <%= link_to gossip.title, gossip_path(gossip) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Ce moussaillon n'a pas encore publié de potin.</p>
  <% end %>
</div>